// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi.Data;

namespace WebApi.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210914094830_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.9");

            modelBuilder.Entity("Core.Domain.Entities.SymbolAggregate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<float>("ClosePrice")
                        .HasColumnType("REAL");

                    b.Property<float>("HighestPrice")
                        .HasColumnType("REAL");

                    b.Property<float>("LowestPrice")
                        .HasColumnType("REAL");

                    b.Property<long>("NumberOfTransactions")
                        .HasColumnType("INTEGER");

                    b.Property<float>("OpenPrice")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("SymbolName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SymbolAggregates");
                });
#pragma warning restore 612, 618
        }
    }
}
